Board.create!([
  {title: "LOLOLOL", user_id: 1},
  {title: "LOLOLOL", user_id: 1},
  {title: "LOLOLOL", user_id: 1},
  {title: "LOLOLOL", user_id: 1},
  {title: "asdf", user_id: 1},
  {title: "asdfasdf", user_id: 1},
  {title: "LOL", user_id: 1}
])
Card.create!([
  {title: "asdfasdf", list_id: 14, description: nil, ord: 0.0},
  {title: "asdfasfd", list_id: 2, description: nil, ord: 0.0},
  {title: "asdfasdf", list_id: 3, description: nil, ord: 0.0},
  {title: "sdfasdfadfasdf", list_id: 1, description: nil, ord: 0.0},
  {title: "lololol", list_id: 10, description: nil, ord: 0.0},
  {title: "asdfasdf", list_id: 8, description: nil, ord: 0.0},
  {title: "LOLOLOL", list_id: 9, description: nil, ord: 0.0},
  {title: "asdfadasfd", list_id: 4, description: nil, ord: 0.0},
  {title: "LOLOLOL", list_id: 7, description: nil, ord: 0.0},
  {title: "lol", list_id: 12, description: nil, ord: 0.0},
  {title: "asdf", list_id: 11, description: nil, ord: 0.0},
  {title: "adsfasdf", list_id: 16, description: nil, ord: 0.0},
  {title: "asdfasdf", list_id: 3, description: nil, ord: 1.0},
  {title: "asdfadfafdasdfasdf", list_id: 4, description: nil, ord: 1.0},
  {title: "asdfasdf", list_id: 10, description: nil, ord: 1.0},
  {title: "asdfa", list_id: 1, description: nil, ord: 1.0},
  {title: "adsfasdfafdsadfasfd", list_id: 2, description: nil, ord: 1.0},
  {title: "asdfasdf", list_id: 8, description: nil, ord: 1.0},
  {title: "asdfasdfasdfasdf", list_id: 3, description: nil, ord: 2.0},
  {title: "iuyfiuyf", list_id: 2, description: nil, ord: 2.0},
  {title: "fFASDFASDFASDF", list_id: 1, description: nil, ord: 2.0},
  {title: "asdfasdf", list_id: 8, description: nil, ord: 2.0},
  {title: "asdfasdf", list_id: 1, description: nil, ord: 3.0},
  {title: "asdfsdf", list_id: 8, description: nil, ord: 3.0},
  {title: "asdf", list_id: 2, description: nil, ord: 3.0},
  {title: "asdfasdf", list_id: 3, description: nil, ord: 3.0},
  {title: "asdfasdf", list_id: 2, description: nil, ord: 4.0},
  {title: "asdfasdf", list_id: 1, description: nil, ord: 4.0},
  {title: "asdfasdf", list_id: 1, description: nil, ord: 5.0},
  {title: "asdfasdf", list_id: 2, description: nil, ord: 5.0},
  {title: "asdfasdfasdf", list_id: 1, description: nil, ord: 6.0},
  {title: "asdfaszdf", list_id: 1, description: nil, ord: 7.0}
])
Item.create!([
  {title: "asdfasfd", card_id: 1, done: true},
  {title: "asdfasdf", card_id: 1, done: true},
  {title: "asdfasdf", card_id: 5, done: false},
  {title: "sfdsgfds\n", card_id: 20, done: false},
  {title: "  LOLOLOL", card_id: 24, done: true},
  {title: "afs asdfasdf", card_id: 24, done: false},
  {title: "asdfasdf", card_id: 26, done: true},
  {title: "asdfasdf", card_id: 27, done: true},
  {title: "LOLOL", card_id: 21, done: false},
  {title: "LOLOL", card_id: 21, done: false},
  {title: "LOLOL", card_id: 22, done: false},
  {title: "LOLOLOL", card_id: 22, done: false},
  {title: "asdf", card_id: 28, done: false},
  {title: "asdfasdfasdf", card_id: 20, done: false},
  {title: "aleiurhaleiuh", card_id: 29, done: false},
  {title: "aethaethaethaasdfa", card_id: 29, done: false},
  {title: "asdfasdf", card_id: 29, done: false},
  {title: "be a troll", card_id: 29, done: false},
  {title: "be a troll", card_id: 22, done: false},
  {title: "LOLOL", card_id: 29, done: false},
  {title: "argaerg", card_id: 28, done: false},
  {title: "lol", card_id: 20, done: false},
  {title: "LOLOL", card_id: 23, done: false},
  {title: "aethaeth", card_id: 23, done: false},
  {title: "aethaeth", card_id: 29, done: false},
  {title: "rdfghjkdfghjkl", card_id: 29, done: false},
  {title: "opoi", card_id: 28, done: false},
  {title: "opy", card_id: 28, done: false},
  {title: "aehaeth", card_id: 28, done: false},
  {title: "ethaethaeth", card_id: 28, done: false},
  {title: "aethaet", card_id: 28, done: false},
  {title: "adgasdf", card_id: 28, done: false},
  {title: "asdf", card_id: 28, done: false},
  {title: "a", card_id: 28, done: false},
  {title: "aerhaeh", card_id: 28, done: false},
  {title: "ekywy5jwsjy", card_id: 28, done: false},
  {title: "4tahrth aerg", card_id: 28, done: false},
  {title: "AETJ AERTHJARG", card_id: 28, done: false},
  {title: "asdfasdh", card_id: 20, done: false},
  {title: "aethaeth", card_id: 20, done: false},
  {title: "aethaeth", card_id: 20, done: false},
  {title: "aethaeth", card_id: 29, done: false},
  {title: "aethaethaeth", card_id: 29, done: false},
  {title: "eath", card_id: 20, done: false},
  {title: "aethaeth", card_id: 28, done: false},
  {title: "aethaeth", card_id: 21, done: false},
  {title: "aetaethaethaet", card_id: 22, done: false},
  {title: "eathaeth", card_id: 23, done: false},
  {title: "asethae", card_id: 23, done: false},
  {title: "aethaeth", card_id: 23, done: false},
  {title: "asdfasdf", card_id: 3, done: false},
  {title: "asdf", card_id: 3, done: false}
])
List.create!([
  {title: "LOLOLOL", board_id: 7, ord: 0.0},
  {title: "asdf", board_id: 6, ord: 0.0},
  {title: ",ukygugoiu", board_id: 3, ord: 0.0},
  {title: "aasdf", board_id: 4, ord: 0.0},
  {title: "adfasdfasdfasdf", board_id: 3, ord: 1.0},
  {title: "asdfasdf", board_id: 7, ord: 1.0},
  {title: "lol", board_id: 6, ord: 1.0},
  {title: "asdf", board_id: 4, ord: 1.0},
  {title: "asdfasdf", board_id: 7, ord: 2.0},
  {title: "lol", board_id: 3, ord: 2.0},
  {title: "asdf", board_id: 4, ord: 2.0},
  {title: "asdfasdf", board_id: 7, ord: 3.0},
  {title: "asdf", board_id: 4, ord: 3.0},
  {title: "asdfasdfafs", board_id: 3, ord: 3.0},
  {title: "asdfasdfasdfasdf", board_id: 3, ord: 4.0},
  {title: "asdfasdfasdfasdfasdf", board_id: 3, ord: 5.0}
])
User.create!([
  {email: "LOL", password_digest: "$2a$10$stSWLtp6NGqaK.y0c1UMueO0kom3T2AkBecU3Pavxmg7xpCwCH3g.", session_token: "TfFz9IgSsYiDlCjFw1MK8A"},
  {email: "lolol", password_digest: "$2a$10$nyd7tfFx9gNiPcKjm0YyT.FpDPRoXp6hGpvfiy909MB79y025eb0G", session_token: "yHfzTUMayTf6Ri-mJdCbyQ"},
  {email: "asdf", password_digest: "$2a$10$aWgUgIHJQxKPVFbSIQ0EXOwA9l6DKcNx7w.9CCayz8hgzPVEpUDRG", session_token: "EoukWKXrngiHqZaqHjzhjg"}
])
